### PR TITLE
romanian localization

### PR DESCRIPTION
**Pull request by Jobava**
This is a Romanian localization for this app.

I am not familiar with the L20n format, so please verify that the file format is ok.

Here is also a diff:
http://sprunge.us/ajCA?diff

Regards

### CODE REVIEW

**Comment by mathroc** [comment]
thank you! the diff looks fine, I'll test that soon to make sure it's working before merging it and making a new release.
I forgot to ask you, can you also add the `ro` locale there : https://github.com/texthtml/place/blob/develop/src/place.js#L19 ?

**Comment by Jobava** [comment]
ok, changes made in place.js as well

**Comment by mathroc** [comment]
thx a lot and sorry for taking so long, I'll try to submit the app with your translation today

**Comment by mathroc** [comment]
oh, there is the app description (for the markerplace) that was not in the translation file. It's just "Simple Foursquare client" if you can translate that too that would be great @Jobava :)

**Comment by Jobava** [comment]
If it's just one string, the translation is: "Client simplu de Foursquare"

**Comment by mathroc** [comment]
thank you, the new version is "Pending approval"

**Pull request merged**
